services:
  - type: web
    name: globaltranscribe-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
